export const projectsData = [
  {
    id: 1,
    title: "Portfolio Website",
    emoji: "🌟",
    description:
      "A modern, animated portfolio website built with Next.js and Framer Motion. Features developer humor, interactive animations, and a beautiful dark theme.",
    technologies: [
      "Next.js",
      "React",
      "Framer Motion",
      "Tailwind CSS",
      "JavaScript",
    ],
    features: [
      "Smooth page transitions and animations",
      "Developer-themed humor and easter eggs",
      "Responsive design with modern UI/UX",
      "Interactive particle effects",
      "Matrix rain background effects",
    ],
    developerComment:
      "This is the website you're currently viewing! Meta, right?",
    backgroundCode: `function Portfolio() {\n  const [isAwesome, setAwesome] = useState(true);\n  \n  useEffect(() => {\n    console.log('Welcome to my portfolio!');\n  }, []);\n  \n  return (\n    <div className="developer-dreams">\n      {isAwesome && <Magic />}\n    </div>\n  );\n}`,
    floatingCode: "// You are here",
    easterEgg: "Inception level: Portfolio",
    isNew: true,
    liveUrl: "#",
    githubUrl: "https://github.com/yourusername/portfolio",
  },
  {
    id: 2,
    title: "E-Commerce Platform",
    emoji: "🛒",
    description:
      "A full-stack e-commerce solution with user authentication, payment integration, and admin dashboard. Built with MERN stack.",
    technologies: ["React", "Node.js", "Express", "MongoDB", "Stripe", "JWT"],
    features: [
      "User authentication and authorization",
      "Shopping cart and wishlist functionality",
      "Secure payment processing with Stripe",
      "Admin dashboard for inventory management",
      "Order tracking and email notifications",
    ],
    developerComment:
      "Where shopping meets code - my first dive into e-commerce!",
    backgroundCode: `const shop = {\n  products: [],\n  cart: [],\n  \n  addToCart(product) {\n    this.cart.push(product);\n    console.log('Ka-ching! 💰');\n  },\n  \n  checkout() {\n    return 'Money well spent!';\n  }\n};`,
    floatingCode: "// Money = Code",
    easterEgg: "Buy one bug, get one feature free!",
    liveUrl: "https://demo-shop.com",
    githubUrl: "https://github.com/yourusername/ecommerce",
  },
  {
    id: 3,
    title: "Task Management App",
    emoji: "📋",
    description:
      "A collaborative task management application with real-time updates, drag-and-drop functionality, and team collaboration features.",
    technologies: ["React", "Node.js", "Socket.io", "MongoDB", "Express"],
    features: [
      "Real-time collaboration with Socket.io",
      "Drag and drop task management",
      "Team workspaces and permissions",
      "Due date reminders and notifications",
      "Progress tracking and analytics",
    ],
    developerComment:
      "Ironically, I procrastinated building this productivity app",
    backgroundCode: `class TaskManager {\n  constructor() {\n    this.tasks = [];\n    this.procrastination = 0;\n  }\n  \n  addTask(task) {\n    this.tasks.push(task);\n    // TODO: Actually do the task\n  }\n}`,
    floatingCode: "// TODO: Finish TODO app",
    easterEgg: "Task: Build task app ✅",
    liveUrl: "https://task-master.com",
    githubUrl: "https://github.com/yourusername/task-manager",
  },
  {
    id: 4,
    title: "Weather Dashboard",
    emoji: "🌤️",
    description:
      "A beautiful weather application with detailed forecasts, interactive maps, and location-based weather alerts.",
    technologies: ["React", "Weather API", "Leaflet.js", "Chart.js", "CSS3"],
    features: [
      "Current weather and 7-day forecast",
      "Interactive weather maps",
      "Location-based weather alerts",
      "Historical weather data charts",
      "Multiple location tracking",
    ],
    developerComment: "Can predict weather better than my deployment schedule",
    backgroundCode: `const weather = {\n  forecast: 'Cloudy with a chance of bugs',\n  temperature: 'Hot like my laptop',\n  \n  predict() {\n    return Math.random() > 0.5 ? '☀️' : '🌧️';\n  }\n};`,
    floatingCode: "// Forecast: 100% chance of coding",
    easterEgg: "It's always sunny in JavaScript",
    liveUrl: "https://weather-dash.com",
    githubUrl: "https://github.com/yourusername/weather-app",
  },
  {
    id: 5,
    title: "Chat Application",
    emoji: "💬",
    description:
      "A real-time chat application with rooms, file sharing, and emoji reactions. Features end-to-end message encryption.",
    technologies: ["React", "Node.js", "Socket.io", "Redis", "Express"],
    features: [
      "Real-time messaging with Socket.io",
      "Private and group chat rooms",
      "File and image sharing",
      "Emoji reactions and stickers",
      "Message search and history",
    ],
    developerComment: "Where developers come to debug their social skills",
    backgroundCode: `socket.on('message', (data) => {\n  console.log('New message:', data);\n  \n  if (data.includes('bug')) {\n    socket.emit('panic', '🚨');\n  }\n});`,
    floatingCode: "// Hello World! 👋",
    easterEgg: "404: Social life not found",
    liveUrl: "https://chat-central.com",
    githubUrl: "https://github.com/yourusername/chat-app",
  },
  {
    id: 6,
    title: "Recipe Finder",
    emoji: "🍳",
    description:
      "A recipe discovery platform with ingredient-based search, meal planning, and grocery list generation. Perfect for food lovers!",
    technologies: [
      "React",
      "Recipe API",
      "Local Storage",
      "CSS Grid",
      "JavaScript",
    ],
    features: [
      "Search recipes by ingredients",
      "Dietary restriction filters",
      "Meal planning calendar",
      "Automatic grocery list generation",
      "Favorite recipes collection",
    ],
    developerComment:
      "Built this because I can only cook instant noodles and despair",
    backgroundCode: `const recipe = {\n  ingredients: ['coffee', 'more coffee'],\n  instructions: [\n    'Open IDE',\n    'Add coffee',\n    'Code until dawn'\n  ],\n  servings: 'feeds one hungry developer'\n};`,
    floatingCode: "// Cooking === Coding?",
    easterEgg: "Secret ingredient: Stack Overflow",
    liveUrl: "https://recipe-hunter.com",
    githubUrl: "https://github.com/yourusername/recipe-finder",
  },
];
